[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/apple-app-site-association"
  to = "/apple-app-site-association"
  status = 200
  force = true

[[redirects]]
  from = "/share/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
